/**
 * Load test: login, load bracket page, save picks.
 *
 * Prerequisites:
 *   1. Seed load-test users:  npx tsx scripts/seed-load-test-users.ts 120
 *   2. Install k6:            https://k6.io/docs/getting-started/installation/
 *
 * Run (default base URL http://localhost:3000):
 *   k6 run load-test/k6.js
 *
 * Run against a deployed URL:
 *   k6 run -e BASE_URL=https://your-app.vercel.app load-test/k6.js
 *
 * Run with more VUs or longer duration:
 *   k6 run --vus 100 --duration 3m load-test/k6.js
 */

import http from 'k6/http';
import { check, sleep } from 'k6';

const BASE_URL = __ENV.BASE_URL || 'http://localhost:3000';

// Load credentials (generated by scripts/seed-load-test-users.ts)
let users = [];
try {
  users = JSON.parse(open('./load-test-users.json'));
} catch (e) {
  console.error('Missing load-test-users.json. Run: npx tsx scripts/seed-load-test-users.ts 120');
  throw e;
}

export const options = {
  scenarios: {
    ramp_then_steady: {
      executor: 'ramping-vus',
      startVUs: 0,
      stages: [
        { duration: '30s', target: 50 },
        { duration: '30s', target: 100 },
        { duration: '2m', target: 100 },
      ],
      gracefulRampDown: '15s',
      gracefulStop: '10s',
      startTime: '0s',
    },
  },
  thresholds: {
    http_req_failed: ['rate<0.05'],
    http_req_duration: ['p(95)<3000'],
  },
};

function makePicks() {
  const picks = {};
  const rounds = [
    [1, 32],
    [2, 16],
    [3, 8],
    [4, 4],
    [5, 2],
    [6, 1],
  ];
  for (const [round, count] of rounds) {
    for (let s = 1; s <= count; s++) {
      picks[`r${round}-${s}`] = Math.random() < 0.5 ? 0 : 1;
    }
  }
  return picks;
}

export default function () {
  const user = users[__VU % users.length];
  if (!user || !user.entryId) return;

  // 1. Login (form POST, follow redirects; cookie is stored in VU jar)
  const loginRes = http.post(`${BASE_URL}/api/auth/login`, {
    username: user.username,
    password: user.password,
  });

  const loginOk = check(loginRes, {
    'login status 2xx or 3xx': (r) => r.status >= 200 && r.status < 400,
  });
  if (!loginOk) {
    console.warn(`Login failed for ${user.username}: ${loginRes.status}`);
    sleep(1);
    return;
  }

  sleep(0.5 + Math.random() * 0.5);

  // 2. Load home (bracket list)
  const homeRes = http.get(`${BASE_URL}/`);
  check(homeRes, { 'home status 200': (r) => r.status === 200 });
  sleep(0.3 + Math.random() * 0.4);

  // 3. Load bracket entry page
  const bracketRes = http.get(`${BASE_URL}/brackets/${user.entryId}`);
  check(bracketRes, { 'bracket page status 200': (r) => r.status === 200 });
  sleep(0.2 + Math.random() * 0.5);

  // 4. Save picks (partial or full)
  const body = JSON.stringify({
    picks: makePicks(),
    championshipTotal: String(120 + Math.floor(Math.random() * 40)),
  });
  const saveRes = http.post(`${BASE_URL}/api/entries/${user.entryId}/picks`, body, {
    headers: { 'Content-Type': 'application/json' },
  });

  check(saveRes, {
    'save picks status 200': (r) => r.status === 200,
    'save picks body ok': (r) => {
      try {
        const j = JSON.parse(r.body);
        return j && j.ok === true;
      } catch {
        return false;
      }
    },
  });

  sleep(1 + Math.random() * 2);
}
